// Mapování názvů zemí z WeatherAPI (vrací je anglicky, případně v jiném
// jazyce dle své vlastní databáze — parametr lang na location.country
// nemá vliv, viz README) na český název.
const COUNTRY_TRANSLATIONS = {
  "Afghanistan": "Afghánistán",
  "Albania": "Albánie",
  "Algeria": "Alžírsko",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Antigua and Barbuda": "Antigua a Barbuda",
  "Argentina": "Argentina",
  "Armenia": "Arménie",
  "Australia": "Austrálie",
  "Austria": "Rakousko",
  "Azerbaijan": "Ázerbájdžán",
  "Bahamas": "Bahamy",
  "Bahrain": "Bahrajn",
  "Bangladesh": "Bangladéš",
  "Barbados": "Barbados",
  "Belarus": "Bělorusko",
  "Belgium": "Belgie",
  "Belize": "Belize",
  "Benin": "Benin",
  "Bhutan": "Bhútán",
  "Bolivia": "Bolívie",
  "Bosnia and Herzegovina": "Bosna a Hercegovina",
  "Botswana": "Botswana",
  "Brazil": "Brazílie",
  "Brunei": "Brunej",
  "Bulgaria": "Bulharsko",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodia": "Kambodža",
  "Cameroon": "Kamerun",
  "Canada": "Kanada",
  "Cape Verde": "Kapverdy",
  "Central African Republic": "Středoafrická republika",
  "Chad": "Čad",
  "Chile": "Chile",
  "China": "Čína",
  "Colombia": "Kolumbie",
  "Comoros": "Komory",
  "Congo": "Kongo",
  "Democratic Republic of the Congo": "Konžská demokratická republika",
  "Costa Rica": "Kostarika",
  "Croatia": "Chorvatsko",
  "Cuba": "Kuba",
  "Cyprus": "Kypr",
  "Czech Republic": "Česká republika",
  "Czechia": "Česko",
  "République Tchèque": "Česká republika",
  "Denmark": "Dánsko",
  "Djibouti": "Džibutsko",
  "Dominica": "Dominika",
  "Dominican Republic": "Dominikánská republika",
  "East Timor": "Východní Timor",
  "Ecuador": "Ekvádor",
  "Egypt": "Egypt",
  "El Salvador": "Salvador",
  "Equatorial Guinea": "Rovníková Guinea",
  "Eritrea": "Eritrea",
  "Estonia": "Estonsko",
  "Eswatini": "Eswatini",
  "Ethiopia": "Etiopie",
  "Fiji": "Fidži",
  "Finland": "Finsko",
  "France": "Francie",
  "Gabon": "Gabon",
  "Gambia": "Gambie",
  "Georgia": "Gruzie",
  "Germany": "Německo",
  "Ghana": "Ghana",
  "Greece": "Řecko",
  "Grenada": "Grenada",
  "Guatemala": "Guatemala",
  "Guinea": "Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  "Guyana": "Guyana",
  "Haiti": "Haiti",
  "Honduras": "Honduras",
  "Hungary": "Maďarsko",
  "Iceland": "Island",
  "India": "Indie",
  "Indonesia": "Indonésie",
  "Iran": "Írán",
  "Iraq": "Irák",
  "Ireland": "Irsko",
  "Israel": "Izrael",
  "Italy": "Itálie",
  "Ivory Coast": "Pobřeží slonoviny",
  "Jamaica": "Jamajka",
  "Japan": "Japonsko",
  "Jordan": "Jordánsko",
  "Kazakhstan": "Kazachstán",
  "Kenya": "Keňa",
  "Kiribati": "Kiribati",
  "Kosovo": "Kosovo",
  "Kuwait": "Kuvajt",
  "Kyrgyzstan": "Kyrgyzstán",
  "Laos": "Laos",
  "Latvia": "Lotyšsko",
  "Lebanon": "Libanon",
  "Lesotho": "Lesotho",
  "Liberia": "Libérie",
  "Libya": "Libye",
  "Liechtenstein": "Lichtenštejnsko",
  "Lithuania": "Litva",
  "Luxembourg": "Lucembursko",
  "Madagascar": "Madagaskar",
  "Malawi": "Malawi",
  "Malaysia": "Malajsie",
  "Maldives": "Maledivy",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marshall Islands": "Marshallovy ostrovy",
  "Mauritania": "Mauritánie",
  "Mauritius": "Mauricius",
  "Mexico": "Mexiko",
  "Micronesia": "Mikronésie",
  "Moldova": "Moldavsko",
  "Monaco": "Monako",
  "Mongolia": "Mongolsko",
  "Montenegro": "Černá Hora",
  "Morocco": "Maroko",
  "Mozambique": "Mosambik",
  "Myanmar": "Myanmar",
  "Namibia": "Namibie",
  "Nauru": "Nauru",
  "Nepal": "Nepál",
  "Netherlands": "Nizozemsko",
  "New Zealand": "Nový Zéland",
  "Nicaragua": "Nikaragua",
  "Niger": "Niger",
  "Nigeria": "Nigérie",
  "North Korea": "Severní Korea",
  "North Macedonia": "Severní Makedonie",
  "Norway": "Norsko",
  "Oman": "Omán",
  "Pakistan": "Pákistán",
  "Palau": "Palau",
  "Palestine": "Palestina",
  "Panama": "Panama",
  "Papua New Guinea": "Papua Nová Guinea",
  "Paraguay": "Paraguay",
  "Peru": "Peru",
  "Philippines": "Filipíny",
  "Poland": "Polsko",
  "Portugal": "Portugalsko",
  "Qatar": "Katar",
  "Romania": "Rumunsko",
  "Russia": "Rusko",
  "Rwanda": "Rwanda",
  "Saint Kitts and Nevis": "Svatý Kryštof a Nevis",
  "Saint Lucia": "Svatá Lucie",
  "Saint Vincent and the Grenadines": "Svatý Vincenc a Grenadiny",
  "Samoa": "Samoa",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "Svatý Tomáš a Princův ostrov",
  "Saudi Arabia": "Saúdská Arábie",
  "Senegal": "Senegal",
  "Serbia": "Srbsko",
  "Seychelles": "Seychely",
  "Sierra Leone": "Sierra Leone",
  "Singapore": "Singapur",
  "Slovakia": "Slovensko",
  "Slovenia": "Slovinsko",
  "Solomon Islands": "Šalomounovy ostrovy",
  "Somalia": "Somálsko",
  "South Africa": "Jihoafrická republika",
  "South Korea": "Jižní Korea",
  "South Sudan": "Jižní Súdán",
  "Spain": "Španělsko",
  "Sri Lanka": "Srí Lanka",
  "Sudan": "Súdán",
  "Suriname": "Surinam",
  "Sweden": "Švédsko",
  "Switzerland": "Švýcarsko",
  "Syria": "Sýrie",
  "Taiwan": "Tchaj-wan",
  "Tajikistan": "Tádžikistán",
  "Tanzania": "Tanzanie",
  "Thailand": "Thajsko",
  "Togo": "Togo",
  "Tonga": "Tonga",
  "Trinidad and Tobago": "Trinidad a Tobago",
  "Tunisia": "Tunisko",
  "Turkey": "Turecko",
  "Turkmenistan": "Turkmenistán",
  "Tuvalu": "Tuvalu",
  "Uganda": "Uganda",
  "Ukraine": "Ukrajina",
  "United Arab Emirates": "Spojené arabské emiráty",
  "United Kingdom": "Spojené království",
  "United States of America": "Spojené státy americké",
  "United States": "Spojené státy americké",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Uzbekistán",
  "Vanuatu": "Vanuatu",
  "Vatican City": "Vatikán",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Yemen": "Jemen",
  "Zambia": "Zambie",
  "Zimbabwe": "Zimbabwe",
};

function translateCountry(name) {
  return COUNTRY_TRANSLATIONS[name] || name;
}
